# roles/yum_cron/tasks/main.yml
---
- name: install yum-cron
  yum:
    name: yum-cron
    state: present

- name: make sure yum-cron service is enabled and running
  service:
    name: yum-cron
    state: started
    enabled: yes
